Friend Module Counters
    Friend Const BEWWY_HERTZ As String = NameOf(BEWWY_HERTZ)
    Friend Const DISTANCE_REMAINING As String = NameOf(DISTANCE_REMAINING)
    Friend Const DRIVING_INSTRUCTION As String = NameOf(DRIVING_INSTRUCTION)
    Friend Const FATIGUE As String = NameOf(FATIGUE)
    Friend Const FORAGE_EXPERIENCE As String = NameOf(FORAGE_EXPERIENCE)
    Friend Const FLOWERS_REMAINING As String = NameOf(FLOWERS_REMAINING)
    Friend Const FORAGE_SKILL As String = NameOf(FORAGE_SKILL)
    Friend Const FORAGING_DIFFICULTY As String = NameOf(FORAGING_DIFFICULTY)
    Friend Const HEALTH As String = NameOf(HEALTH)
    Friend Const JOOLS As String = NameOf(JOOLS)
    Friend Const LITTERING As String = NameOf(LITTERING)
    Friend Const PACE As String = NameOf(PACE)
    Friend Const RECYCLING As String = NameOf(RECYCLING)
    Friend Const SATIETY As String = NameOf(SATIETY)
    Friend Const SNAX As String = NameOf(SNAX)
    Friend Const STOMACH As String = NameOf(STOMACH)
End Module
